### ISSUE TITLE
Unhandled Exception has occurred in your application.

### ISSUE THREAD

**Issue by CaineYane** [luttje/Key2Joy#84]
I get an unhandled exception error every time I check mark the "enable" box for button mappings, followed by an "Access to the path is denied." message. I also get this message box every time I try to create a new mapping of my own, open the program, and change anything in the program. How do I fix this? Is this normal? I've tried to run the program as administrator/gave it full access and it still occurs 

Full message box log below:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
   at System.IO.File.AppendAllText(String path, String contents)
   at Key2Joy.Output.WriteLine(Object[] parts) in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Output.cs:line 64
   at Key2Joy.Mapping.LuaScriptAction.RegisterScriptingMethod(String functionName, BaseAction instance, MethodInfo method) in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Mapping\Actions\Scripting\LuaScriptAction.cs:line 62
   at Key2Joy.Mapping.BaseScriptActionWithEnvironment`1.RegisterEnvironmentObjects() in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Mapping\Actions\Scripting\BaseScriptActionWithEnvironment.cs:line 57
   at Key2Joy.Mapping.LuaScriptAction.RegisterEnvironmentObjects() in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Mapping\Actions\Scripting\LuaScriptAction.cs:line 113
   at Key2Joy.Mapping.BaseScriptActionWithEnvironment`1.OnStartListening(TriggerListener listener, List`1& otherActions) in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Mapping\Actions\Scripting\BaseScriptActionWithEnvironment.cs:line 86
   at Key2Joy.Mapping.LuaScriptAction.OnStartListening(TriggerListener listener, List`1& otherActions) in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Mapping\Actions\Scripting\LuaScriptAction.cs:line 118
   at Key2Joy.Key2JoyManager.ArmMappings(MappingProfile profile) in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy\Key2JoyManager.cs:line 133
   at Key2Joy.Gui.MainForm.ChkEnabled_CheckedChanged(Object sender, EventArgs e) in D:\Projects\_Personal\Windows\Key2Joy\Key2Joy.Gui\MainForm.cs:line 310
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Key2Joy
    Assembly Version: 0.6.0.0
    Win32 Version: 0.6.0.0
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/Key2Joy.exe
----------------------------------------
Key2Joy.Core
    Assembly Version: 0.6.0.0
    Win32 Version: 0.6.0.0
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/Key2Joy.Core.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
FFMpegCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/FFMpegCore.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
SimWinGamePad
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/SimWinGamePad.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.2
    Win32 Version: 6.0.222.6406
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/System.Text.Json.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9195.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/ObjectListView.DLL
----------------------------------------
Jint
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/Jint.DLL
----------------------------------------
NLua
    Assembly Version: 1.6.0.0
    Win32 Version: 1.6.0.0
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/NLua.DLL
----------------------------------------
KeraLua
    Assembly Version: 1.3.1.0
    Win32 Version: 1.3.1.0
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/KeraLua.DLL
----------------------------------------
RawInput.Sharp
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Key2Joy-0.6.0%20(1)/RawInput.Sharp.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by luttje** [comment]
Hi there! Sorry to hear that you've run into this issue. Good to hear that you've already tried some smart things to problem solve it.

I see that you closed the issue already, did you manage to work around the problem?

This does seem like a bug in version 0.6.0.0, where [the wrong](https://github.com/luttje/Key2Joy/blob/fe638f3dac8b3fbdf8c692c02364d9ddb845bdb5/Key2Joy/Output.cs#L36) log directory is attempted to be written to. Instead of writing to [the My Documents Key2Joy folder](https://github.com/luttje/Key2Joy/blob/3bfa3ba362212aab096d1ca54574c8d02939f869/Core/Key2Joy.Contracts/Output.cs#L53), I think it tries to write logs to a Logs directory in wherever Key2Joy is installed. A workaround might be to Key2Joy in a location where no such problem could occur.

Sadly I am not working on this project much, so I won't be fixing 0.6.0.0, nor any newer version any time soon. But do let me know if the issue persists, that way I can get to it when I'm working on this again in the future.

Thanks!
